## <span style='background:rgb(0,255,255)' ><font color='black'>**Import OptiDamTool**</font></span>

In [1]:
import IPython
import OptiDamTool
import os

# mutiple output visibility from a single cell
IPython.InteractiveShell.ast_node_interactivity = 'all'

## <span style='background:rgb(0,255,255)' ><font color='black'>**Classes**</font></span>

In [2]:
watemsedem = OptiDamTool.WatemSedem()
network = OptiDamTool.Network()
analysis = OptiDamTool.Analysis()

## <span style='background:rgb(0,255,255)' ><font color='black'>**Class Directory**</font></span>

In [3]:
dir_watemsedem = [i for i in dir(watemsedem) if not i.startswith('_')]
dir_watemsedem

dir_network = [i for i in dir(network) if not i.startswith('_')]
dir_network

dir_analysis = [i for i in dir(analysis) if not i.startswith('_')]
dir_analysis

['dam_effective_drainage_polygon',
 'dem_to_stream',
 'file',
 'land_cover_esri',
 'land_cover_mapping',
 'land_management_factor',
 'land_management_mapping',
 'model_region_extension',
 'raster',
 'raster_clipping_by_bounding_box',
 'raster_constant_extension',
 'raster_driver_to_rst',
 'raster_extension',
 'raster_reproject_clipping_rescaling',
 'rusle_kr',
 'shape',
 'stream',
 'watershed']

['connectivity_adjacent_downstream',
 'connectivity_adjacent_upstream',
 'effective_drainage_area',
 'effective_sediment_inflow',
 'effective_upstream_metrics_summary']

['raster_features_retrieve',
 'sediment_delivery_to_stream_shapefile',
 'sediment_delivery_to_stream_txt',
 'sediment_summary_dynamics_region']

## <span style='background:rgb(0,255,255)' ><font color='black'>**Data Folder Paths**</font></span>

In [4]:
current_dir = os.getcwd()

# download the 'data' folder from 'https://github.com/debpal/OptiDamTool/tree/main/tests/data' folder and adjust this path for your computer system.
data_folder = os.path.join(current_dir, 'tests', 'data')

# the output folder path needs to be adjusted according to the user's computer system
output_folder = os.path.join(os.path.dirname(current_dir), 'output_OptiDamTool')

## <span style='background:rgb(0,255,255)' ><font color='black'>**Methods of WatemSedem Class**</font></span>

### <span style='background:orange' ><font color='black'>**DEM to Stream Files**</font></span>

In [6]:
output = watemsedem.dem_to_stream(
    dem_file=os.path.join(data_folder, 'dem.tif'),
    flwacc_percent=2,
    folder_path=output_folder
)

output

DEM reading time (seconds): 0.27
Pit filling and flow direction calculation time (seconds): 14.32
Slope calculation time (seconds): 1.95
Aspect calculation time (seconds): 1.01
Flow accumulation calculation time (seconds): 5.47
Stream calculation time (seconds): 1.96
Subbasin calculation time (seconds): 2.5
Total time (seconds): 27.6

Stream raster creation complete

Stream routing raster creation complete

,ws_id,geometry,ds_id,isa_m2,flwacc,csa_m2
0,1,"LINESTRING (321472.614 1950186.424, 321442.614...",8,439697700.0,488553,4.396977e+08
1,2,"LINESTRING (310942.614 1924446.424, 310912.614...",6,238311000.0,264790,2.383110e+08
2,3,"LINESTRING (315292.614 1934556.424, 315262.614...",6,284752800.0,316392,2.847528e+08
3,4,"LINESTRING (305932.614 1944876.424, 305902.614...",7,201430800.0,223812,2.014308e+08
4,5,"LINESTRING (306142.614 1954806.424, 306112.614...",8,210636900.0,234041,2.106369e+08
5,6,"LINESTRING (301852.614 1935996.424, 301852.614...",7,48444300.0,635009,5.715081e+08
6,7,"LINESTRING (298222.614 1942926.424, 298192.614...",10,17389800.0,878143,7.903287e+08
7,8,"LINESTRING (297802.614 1950936.424, 297772.614...",10,32929200.0,759182,6.832638e+08
8,9,"LINESTRING (317512.614 1970766.424, 317482.614...",15,512829900.0,569811,5.128299e+08
9,10,"LINESTRING (293962.614 1947366.424, 293932.614...",14,57178800.0,1700857,1.530771e+09
10,11,"LINESTRING (303982.614 1980456.424, 303952.614...",15,317579400.0,352866,3.175794e+08
11,12,"LINESTRING (291622.614 1988676.424, 291592.614...",16,648546300.0,720607,6.485463e+08
12,13,"LINESTRING (288232.614 1948416.424, 288232.614...",14,160238700.0,178043,1.602387e+08
13,14,"LINESTRING (288262.614 1948626.424, 288232.614...",17,279806400.0,2189796,1.970816e+09
14,15,"LINESTRING (293392.614 1965696.424, 293362.614...",16,122808600.0,1059131,9.532179e+08
15,16,"LINESTRING (283012.614 1965096.424, 282982.614...",17,8680500.0,1789383,1.610445e+09
16,17,"LINESTRING (281572.614 1964856.424, 281542.614...",19,446216400.0,4474975,4.027478e+09
17,18,"LINESTRING (254092.614 1977126.424, 254092.614...",19,262321200.0,291468,2.623212e+08
18,19,"LINESTRING (256402.614 1966926.424, 256372.614...",21,182468700.0,4969186,4.472267e+09
19,20,"LINESTRING (259252.614 1952526.424, 259222.614...",21,249630300.0,277367,2.496303e+08
20,21,"LINESTRING (251932.614 1955316.424, 251902.614...",28,228720600.0,5500687,4.950618e+09
21,22,"LINESTRING (287302.614 1917066.424, 287272.614...",27,324386100.0,360429,3.243861e+08
22,23,"LINESTRING (251182.614 1934076.424, 251152.614...",28,401868000.0,446520,4.018680e+08
23,24,"LINESTRING (259222.614 1931466.424, 259192.614...",29,232859700.0,258733,2.328597e+08
24,25,"LINESTRING (271672.614 1909296.424, 271642.614...",27,355851000.0,395390,3.558510e+08
25,26,"LINESTRING (257092.614 1914096.424, 257062.614...",29,341994600.0,379994,3.419946e+08
26,27,"LINESTRING (261922.614 1899906.424, 261922.614...",33,103265100.0,870558,7.835022e+08
27,28,"LINESTRING (243892.614 1913826.424, 243892.614...",30,7340400.0,5955363,5.359827e+09
28,29,"LINESTRING (246742.614 1911906.424, 246712.614...",30,15192000.0,655607,5.900463e+08
29,30,"LINESTRING (243202.614 1908486.424, 243232.614...",32,97059600.0,6718814,6.046933e+09
30,31,"LINESTRING (243232.614 1899276.424, 243202.614...",32,175558500.0,195065,1.755585e+08
31,32,"LINESTRING (242332.614 1899036.424, 242302.614...",33,59495400.0,6979985,6.281986e+09
32,33,"LINESTRING (236512.614 1891656.424, 236512.614...",-1,10542600.0,7862257,7.076031e+09

### <span style='background:orange' ><font color='black'>**Model Region Extension**</font></span>

In [7]:
output = watemsedem.model_region_extension(
    dem_file=os.path.join(data_folder, 'dem.tif'),
    buffer_units=50,
    folder_path=output_folder
)

output

{'actual area (m^2)': 7076039400,
 'extended area (m^2)': 7806124800,
 'difference area (m^2)': 730085400}

### <span style='background:orange' ><font color='black'>**Raster Clipping by Bounding Box**</font></span>

In [8]:
output = watemsedem.raster_clipping_by_bounding_box(
    input_file=os.path.join(data_folder, 'R_clipped.tif'),
    shape_file=os.path.join(output_folder, 'region_buffer.shp'),
    output_file=os.path.join(output_folder, 'RUSLE_R_region.tif')
)

### <span style='background:orange' ><font color='black'>**Raster Reprojection, Clipping, and Resolution Rescaling**</font></span>

In [9]:
output = watemsedem.raster_reproject_clipping_rescaling(
    input_file=os.path.join(output_folder, 'RUSLE_R_region.tif'),
    resampling_method='bilinear',
    shape_file=os.path.join(output_folder, 'region.shp'),
    mask_file=os.path.join(output_folder, 'region.tif'),
    output_file=os.path.join(output_folder, 'RUSLE_R.tif')
)

### <span style='background:orange' ><font color='black'>**Constant Raster and NoData Replacement**</font></span>

In [10]:
output = watemsedem.raster_constant_extension(
    input_file=os.path.join(output_folder, 'region.tif'),
    constant_value=0.1694,
    region_file=os.path.join(output_folder, 'region.tif'),
    output_file=os.path.join(output_folder, 'RUSLE_K.tif'),
    dtype='float32'
)

### <span style='background:orange' ><font color='black'>**Multiplication of Soil Erodibility and Rainfall Erosivity Factors**</font></span>

In [11]:
output = watemsedem.rusle_kr(
    k_file=os.path.join(output_folder, 'RUSLE_K.tif'),
    r_file=os.path.join(output_folder, 'RUSLE_R.tif'),
    region_file=os.path.join(output_folder, 'region.tif'),
    output_file=os.path.join(output_folder, 'KR.tif'),
    k_multiplier=1000
)

### <span style='background:orange' ><font color='black'>**Esri Land Cover Raster Processing**</font></span>

In [12]:
output = watemsedem.land_cover_esri(
    lc_file=os.path.join(data_folder, 'land_cover_clipped.tif'),
    stream_file=os.path.join(output_folder, 'stream_lines.shp'),
    folder_path=output_folder
)

output

'Total agricultural lands identified: 1417'

### <span style='background:orange' ><font color='black'>**Land Management Factor**</font></span>

In [13]:
output = watemsedem.land_management_factor(
    lc_file=os.path.join(data_folder, 'land_cover_clipped.tif'),
    stream_file=os.path.join(output_folder, 'stream_lines.shp'),
    output_file=os.path.join(output_folder, 'RUSLE_C.tif')
)

output

[np.float32(0.0),
 np.float32(0.013),
 np.float32(0.22),
 np.float32(0.301),
 np.float32(0.374),
 np.float32(1.0)]

### <span style='background:orange' ><font color='black'>**Raster Spatial Extension**</font></span>

In [14]:
output = watemsedem.raster_extension(
    input_file=os.path.join(output_folder, 'stream_lines.tif'),
    fill_value=0,
    region_file=os.path.join(output_folder, 'region_buffer.tif'),
    output_file=os.path.join(output_folder, 'stream_buffer.tif')
)

### <span style='background:orange' ><font color='black'>**Raster Driver Conversion**</font></span>

In [15]:
file_dict = {
    'stream': os.path.join(output_folder, 'stream_buffer.tif')
}

output = watemsedem.raster_driver_to_rst(
    file_dict=file_dict,
    folder_path=output_folder
)

output

['stream.rst']

### <span style='background:orange' ><font color='black'>**Effective Upstream Drainage Polygons of Dams**</font></span>

In [6]:
output = watemsedem.dam_effective_drainage_polygon(
    flwdir_file=os.path.join(data_folder, 'flwdir.tif'),
    location_file=os.path.join(data_folder, 'subbasin_drainage_points.shp'),
    location_col='ws_id',
    dam_list=[21, 22, 5, 31, 17, 24, 27, 2, 13, 1],
    folder_path=output_folder
)

output

                                            geometry  ws_id       area_m2
0  POLYGON ((317557.614 1958751.424, 317557.614 1...    1.0  4.396977e+08
1  POLYGON ((301357.614 1936071.424, 301357.614 1...    2.0  2.383110e+08
2  POLYGON ((321787.614 1965771.424, 321787.614 1...    5.0  2.106369e+08
3  POLYGON ((288247.614 1948611.424, 288247.614 1...   13.0  1.602387e+08
4  POLYGON ((275587.614 1998651.424, 275587.614 1...   17.0  2.978593e+09
5  POLYGON ((262237.614 1992201.424, 262237.614 1...   21.0  9.231408e+08
6  POLYGON ((283117.614 1935951.424, 283117.614 1...   22.0  3.243861e+08
7  POLYGON ((275677.614 1942971.424, 275677.614 1...   24.0  2.328597e+08
8  POLYGON ((282427.614 1936071.424, 282427.614 1...   27.0  4.591161e+08
9  POLYGON ((270217.614 1921941.424, 270217.614 1...   31.0  1.755585e+08

## <span style='background:rgb(0,255,255)' ><font color='black'>**Method of Network Class**</font></span>

### <span style='background:orange' ><font color='black'>**Adjancent Downstream Dam Connectivity**</font></span>

In [16]:
output = network.connectivity_adjacent_downstream(
    stream_file=os.path.join(data_folder, 'stream_lines.shp'),
    stream_col='ws_id',
    dam_list=[21, 22, 5, 31, 17, 24, 27, 2, 13, 1]
)

output

{21: -1, 22: 27, 5: 17, 31: -1, 17: 21, 24: -1, 27: -1, 2: 17, 13: 17, 1: 17}

### <span style='background:orange' ><font color='black'>**Adjancent Upstream Dam Connectivity**</font></span>

In [5]:
output = network.connectivity_adjacent_upstream(
    stream_file=os.path.join(data_folder, 'stream_lines.shp'),
    stream_col='ws_id',
    dam_list=[21, 22, 5, 31, 17, 24, 27, 2, 13, 1]
)

### <span style='background:orange' ><font color='black'>**Effective Upstream Drainage Area of Dams**</font></span>

In [6]:
output = network.effective_drainage_area(
    stream_file=os.path.join(data_folder, 'stream_lines.shp'),
    stream_col='ws_id',
    dam_list=[21, 22, 5, 31, 17, 24, 27, 2, 13, 1]
)

### <span style='background:orange' ><font color='black'>**Effective Sediment Inflow to Dams**</font></span>

In [7]:
output = network.effective_sediment_inflow(
    stream_file=os.path.join(data_folder, 'stream_information_with_sediment_delivery.shp'),
    stream_col='ws_id',
    dam_list=[21, 22, 5, 31, 17, 24, 27, 2, 13, 1]
)

### <span style='background:orange' ><font color='black'>**Effective Upstream Metric Summary of Dams**</font></span>

In [8]:
output = network.effective_upstream_metrics_summary(
    stream_file=os.path.join(data_folder, 'stream_information_with_sediment_delivery.shp'),
    stream_col='ws_id',
    dam_list=[21, 22, 5, 31, 17, 24, 27, 2, 13, 1],
    sort_dam=True
)

output

{'adjacent_upstream_connection': {1: [],
  2: [],
  5: [],
  13: [],
  17: [1, 2, 5, 13],
  21: [17],
  22: [],
  24: [],
  27: [22],
  31: []},
 'effective_drainage_area_m2': {1: 85420840.0,
  2: 99906272.0,
  5: 159078144.0,
  13: 509775.34,
  17: 534348712.66,
  21: 80312832.0,
  22: 68955584.0,
  24: 13756542.0,
  27: 27397520.0,
  31: 1292848.0},
 'effective_sediment_inflow_kg': {1: 85420840.0,
  2: 99906272.0,
  5: 159078144.0,
  13: 509775.34,
  17: 534348712.66,
  21: 80312832.0,
  22: 68955584.0,
  24: 13756542.0,
  27: 27397520.0,
  31: 1292848.0}}

## <span style='background:rgb(0,255,255)' ><font color='black'>**Method of Analysis Class**</font></span>

### <span style='background:orange' ><font color='black'>**Integrating Stream Information with Sediment Inflow**</font></span>

In [9]:
output = analysis.sediment_delivery_to_stream_txt(
    input_file=os.path.join(data_folder, 'stream_information.txt'),
    stream_col='ws_id',
    segsed_file=os.path.join(data_folder, 'Total sediment segments.txt'),
    cumsed_file=os.path.join(data_folder, 'Cumulative sediment segments.txt'),
    output_file=os.path.join(output_folder, 'stream_sediment_delivery.txt')
)

### <span style='background:orange' ><font color='black'>**Stream Shapefile with Sediment Inflow Information**</font></span>

In [27]:
output = analysis.sediment_delivery_to_stream_shapefile(
    stream_file=os.path.join(data_folder, 'stream_lines.shp'),
    sediment_file=os.path.join(output_folder, 'stream_sediment_delivery.txt'),
    output_file=os.path.join(data_folder, 'stream_information_with_sediment_delivery.shp')
)

output

,ws_id,ds_id,isa_m2,flwacc,csa_m2,geometry,sed_kg,cumsed_kg,sed_ton,cumsed_ton
0,1,8,439697700.0,488553.0,4.396977e+08,"LINESTRING (321472.614 1950186.424, 321442.614...",8.542084e+07,8.542084e+07,85420.840000,8.542084e+04
1,2,6,238311000.0,264790.0,2.383110e+08,"LINESTRING (310942.614 1924446.424, 310912.614...",9.990627e+07,9.990627e+07,99906.272000,9.990627e+04
2,3,6,284752800.0,316392.0,2.847528e+08,"LINESTRING (315292.614 1934556.424, 315262.614...",5.201261e+07,5.201261e+07,52012.608000,5.201261e+04
3,4,7,201430800.0,223812.0,2.014308e+08,"LINESTRING (305932.614 1944876.424, 305902.614...",3.891738e+07,3.891738e+07,38917.380000,3.891738e+04
4,5,8,210636900.0,234041.0,2.106369e+08,"LINESTRING (306142.614 1954806.424, 306112.614...",1.590781e+08,1.590781e+08,159078.144000,1.590781e+05
5,6,7,48444300.0,635009.0,5.715081e+08,"LINESTRING (301852.614 1935996.424, 301852.614...",2.433332e+07,1.762522e+08,24333.316000,1.762522e+05
6,7,10,17389800.0,878143.0,7.903287e+08,"LINESTRING (298222.614 1942926.424, 298192.614...",7.815852e+06,2.229854e+08,7815.852000,2.229854e+05
7,8,10,32929200.0,759182.0,6.832638e+08,"LINESTRING (297802.614 1950936.424, 297772.614...",4.269733e+07,2.871963e+08,42697.332000,2.871963e+05
8,9,15,512829900.0,569811.0,5.128299e+08,"LINESTRING (317512.614 1970766.424, 317482.614...",1.026771e+08,1.026771e+08,102677.120000,1.026771e+05
9,10,14,57178800.0,1700857.0,1.530771e+09,"LINESTRING (293962.614 1947366.424, 293932.614...",2.890350e+07,5.390852e+08,28903.504000,5.390852e+05
10,11,15,317579400.0,352866.0,3.175794e+08,"LINESTRING (303982.614 1980456.424, 303952.614...",5.106119e+07,5.106119e+07,51061.192000,5.106119e+04
11,12,16,648546300.0,720607.0,6.485463e+08,"LINESTRING (291622.614 1988676.424, 291592.614...",4.890648e+07,4.890648e+07,48906.484000,4.890648e+04
12,13,14,160238700.0,178043.0,1.602387e+08,"LINESTRING (288232.614 1948416.424, 288232.614...",5.097753e+05,5.097753e+05,509.775344,5.097753e+02
13,14,17,279806400.0,2189796.0,1.970816e+09,"LINESTRING (288262.614 1948626.424, 288232.614...",4.663363e+07,5.862286e+08,46633.632000,5.862286e+05
14,15,16,122808600.0,1059131.0,9.532179e+08,"LINESTRING (293392.614 1965696.424, 293362.614...",1.936497e+07,1.731033e+08,19364.970000,1.731033e+05
15,16,17,8680500.0,1789383.0,1.610445e+09,"LINESTRING (283012.614 1965096.424, 282982.614...",1.782558e+06,2.237923e+08,1782.558250,2.237923e+05
16,17,19,446216400.0,4474975.0,4.027478e+09,"LINESTRING (281572.614 1964856.424, 281542.614...",6.924288e+07,8.792637e+08,69242.880000,8.792637e+05
17,18,19,262321200.0,291468.0,2.623212e+08,"LINESTRING (254092.614 1977126.424, 254092.614...",3.232534e+07,3.232534e+07,32325.336000,3.232534e+04
18,19,21,182468700.0,4969186.0,4.472267e+09,"LINESTRING (256402.614 1966926.424, 256372.614...",1.771297e+07,9.293021e+08,17712.968000,9.293021e+05
19,20,21,249630300.0,277367.0,2.496303e+08,"LINESTRING (259252.614 1952526.424, 259222.614...",1.668298e+07,1.668298e+07,16682.984000,1.668298e+04
20,21,28,228720600.0,5500687.0,4.950618e+09,"LINESTRING (251932.614 1955316.424, 251902.614...",1.359145e+07,9.595766e+08,13591.452000,9.595766e+05
21,22,27,324386100.0,360429.0,3.243861e+08,"LINESTRING (287302.614 1917066.424, 287272.614...",6.895558e+07,6.895558e+07,68955.584000,6.895558e+04
22,23,28,401868000.0,446520.0,4.018680e+08,"LINESTRING (251182.614 1934076.424, 251152.614...",8.887368e+06,8.887368e+06,8887.368000,8.887368e+03
23,24,29,232859700.0,258733.0,2.328597e+08,"LINESTRING (259222.614 1931466.424, 259192.614...",1.375654e+07,1.375654e+07,13756.542000,1.375654e+04
24,25,27,355851000.0,395390.0,3.558510e+08,"LINESTRING (271672.614 1909296.424, 271642.614...",2.129088e+07,2.129088e+07,21290.876000,2.129088e+04
25,26,29,341994600.0,379994.0,3.419946e+08,"LINESTRING (257092.614 1914096.424, 257062.614...",5.260501e+06,5.260501e+06,5260.501000,5.260501e+03
26,27,33,103265100.0,870558.0,7.835022e+08,"LINESTRING (261922.614 1899906.424, 261922.614...",6.106644e+06,9.635310e+07,6106.644500,9.635310e+04
27,28,30,7340400.0,5955363.0,5.359827e+09,"LINESTRING (243892.614 1913826.424, 243892.614...",9.857617e+05,9.694497e+08,985.761687,9.694497e+05
28,29,30,15192000.0,655607.0,5.900463e+08,"LINESTRING (246742.614 1911906.424, 246712.614...",7.644736e+05,1.978152e+07,764.473625,1.978152e+04
29,30,32,97059600.0,6718814.0,6.046933e+09,"LINESTRING (243202.614 1908486.424, 243232.614...",2.134816e+06,9.913660e+08,2134.816500,9.913660e+05
30,31,32,175558500.0,195065.0,1.755585e+08,"LINESTRING (243232.614 1899276.424, 243202.614...",1.292848e+06,1.292848e+06,1292.848000,1.292848e+03
31,32,33,59495400.0,6979985.0,6.281986e+09,"LINESTRING (242332.614 1899036.424, 242302.614...",2.524559e+06,9.951835e+08,2524.559000,9.951835e+05
32,33,-1,10542600.0,7862257.0,7.076031e+09,"LINESTRING (236512.614 1891656.424, 236512.614...",3.185001e+05,1.091855e+09,318.500063,1.091855e+06

### <span style='background:orange' ><font color='black'>**Summary of Total Sediment Dynamics**</font></span>

In [24]:
output = analysis.sediment_summary_dynamics_region(
    input_file=os.path.join(data_folder, 'Total sediment.txt'),
    json_file=os.path.join(data_folder, 'summary.json'),
    output_file=os.path.join(output_folder, 'summary_total_sediment_dynamics.txt')
)

output

,Features,Sediment(kg),area_m2,kg/m2,Sediment(ton),ton/ha
0,Total erosion,-4.516910e+10,7.076039e+09,-6.383388,-4.516910e+07,-63.833879
1,Total deposition,4.407361e+10,7.076039e+09,6.228571,4.407361e+07,62.285706
2,"Sediment leaving the catchment, via the river",1.091855e+09,7.076039e+09,0.154303,1.091855e+06,1.543031
3,"Sediment leaving the catchment, not via the river",1.864294e+06,7.076039e+09,0.000263,1.864294e+03,0.002635

### <span style='background:orange' ><font color='black'>**Retrieve Raster Features**</font></span>

In [26]:
output = analysis.raster_features_retrieve(
    input_file=os.path.join(data_folder, 'WATEREROS_kg.rst'),
    crs_code=32638,
    output_file=os.path.join(output_folder, 'WATEREROS_ton.tif'),
    scale=.001
)